#springdoc:
#  api-docs:
#    enabled: false
#  swagger-ui:
#    url: /open-api.yaml
#    show-extensions: true
#    show-common-extensions: true
#    try-it-out-enabled: true

spring:
#  liquibase:
#    enabled: true

  datasource:
    url: jdbc:postgresql://localhost/spring
    username: postgres
    password: 1122

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        jdbc:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show-sql: true
